# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f69e46fe7c961b4e9d3366040824e0f9a04b8b46b44cb078aae3a0808753ef05339b46343e0049ab4a3d9916f8502fe57fc974a9db33b4efe85091bcb3f6d4f

test:
  secret_key_base: 2c9f61fcbe641ef759e65a8fcbcba7a989327c1d1d9ab72db75816c615a3b75b00fffe33307dd5572a177a92afad1c4b7da82ecf0c7074add8c8538eef2c67a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
