# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eec9d1d830a0832cab9539c935a44636c557b2bdf7c6a4608784ee8749813e730bb7bf311dac70f82bb017053f0e0915ea704c225707845584d0d65d27d4c9df

test:
  secret_key_base: ac211388e2cd80a7c36b5bc32ad98ad8b749623e7cd56c3619b12eafd82343ea05e1eeb0df3b4a93860d022227393d353e8752577b2771f78963d17d18e441ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
